# Generated by Django 2.2.4 on 2019-08-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sort_by',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sort_by',
        ),
    ]
