# Generated by Django 2.2.4 on 2019-08-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_by',
            field=models.CharField(default='Z', max_length=32),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sort_by',
            field=models.CharField(default='Z', max_length=32),
        ),
    ]
