# Generated by Django 2.2.4 on 2019-09-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190826_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-id']},
        ),
    ]
