# Generated by Django 2.2.4 on 2019-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190821_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort_by',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sort_by',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
