# Generated by Django 2.2.4 on 2019-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190824_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sort_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
