# Generated by Django 2.2.4 on 2019-08-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190821_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_delete',
        ),
    ]
