# Generated by Django 2.2.4 on 2019-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190822_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sort_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
