# Generated by Django 2.2 on 2019-10-07 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(blank=True, max_length=64, null=True)),
                ('groupID', models.CharField(blank=True, max_length=64, null=True)),
                ('booking_day', models.DateField(blank=True, null=True)),
                ('action_day', models.DateField(blank=True, null=True)),
                ('action_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=128, null=True)),
                ('variant', models.CharField(blank=True, max_length=64, null=True)),
                ('itinerary', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(1, '餐厅'), (2, '旅游'), (3, '交通'), (4, '租车'), (5, '酒店'), (6, '礼物')], default=2)),
                ('adult_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('child_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('adult_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('child_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('adult_cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('child_cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ref', models.TextField(blank=True, null=True)),
                ('pick_up_time', models.DateTimeField(blank=True, null=True)),
                ('pick_up_address', models.CharField(blank=True, max_length=256, null=True)),
                ('drop_off_address', models.CharField(blank=True, max_length=256, null=True)),
                ('driver', models.CharField(blank=True, max_length=150, null=True)),
                ('driver_mobile', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=64, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=64, null=True)),
                ('guide', models.CharField(blank=True, max_length=150, null=True)),
                ('guide_mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('operator', models.CharField(blank=True, max_length=150, null=True)),
                ('officer', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.IntegerField(choices=[(1, '查询'), (2, '确认'), (3, '等待'), (4, '发送'), (5, '操作取消'), (6, '操作通过')], default=1)),
                ('remark', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('change_at', models.DateTimeField(auto_now=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=64, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-id'],
            },
        ),
    ]
