# Generated by Django 2.2 on 2019-10-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
