# Generated by Django 2.2 on 2019-10-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='adult_cost_price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='adult_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='adult_quantity',
            new_name='quantity',
        ),
    ]
