# Generated by Django 2.2 on 2019-07-14 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190711_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='adultPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sales',
            name='childPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='sales',
            name='child_ticket_desc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
