version: '2'
services:

    db:
      container_name: postgres
      image: postgres
      hostname: db
      environment:
        POSTGRES_PASSWORD: password123
      # ports:
      #   - "5432:5432"
      #   (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/
    
    redis:
      image: redis
      container_name: redis
      hostname: redis
      restart: always
      # ports:
      #   - "6379:6379"
      # extra_hosts:
      #   - "redis:0.0.0.0"
      volumes:
        - redisdata:/data

    nginx:
        container_name: nginx
        build: 
          context: ./
          dockerfile: ./nginx/Dockerfile
        restart: always
        ports:
        - "8080:80"
        volumes:
        - api_data:/docker_api
        - ./log:/var/log/nginx
        depends_on:
        - backend

    backend:
        container_name: backend
        build: ./backend
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
        - api_data:/docker_api
        links:
          - db
          - redis
        depends_on:
        - db
        - redis

    # frontend:
    #   container_name: frontend
    #   build: ./frontend
    #   ports:
    #     - '8080:8080'
    #   links:
    #     - backend

volumes:
    api_data:
    pgdata:
    redisdata: