version: '3.3'
services:

    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_PASSWORD: password123
      # ports:
      #   - "5432:5432"
      #   (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/
    
    redis:
      image: redis
      container_name: redis
      restart: always
      # ports:
      # - "6379:6380"
      volumes:
      - 'redisdata:/data'

    nginx:
        container_name: nginx
        build: ./nginx
        restart: always
        ports:
        # - "8001:8001"
        - "8080:80"
        volumes:
        - api_data:/docker_api
        - ./log:/var/log/nginx
        depends_on:
        - backend

    backend:
        container_name: backend
        build: ./backend
        restart: always
        # command: uwsgi  --emperor uwsgi.ini
        command: uwsgi --ini uwsgi.ini
        volumes:
        - api_data:/docker_api
        depends_on:
        - db
        - redis

volumes:
    api_data:
    pgdata:
    redisdata: