version: '3'
services:

  db:
    container_name: postgres
    image: postgres
    hostname: db
    environment:
      POSTGRES_PASSWORD: password123
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - database_network
  
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - redis_network

  nginx:
    container_name: nginx
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      # - ./nginx/conf.d:/etc/nginx/conf.d/:rw
      ./nginx/conf.d/slave.conf:/etc/nginx/conf.d/slave.conf
      - ./frontend/dist:/frontend/dist/
      - static_volume:/backend/static
      - media_volume:/backend/media
    depends_on:
      - backend
    networks:
      - nginx_network

  backend:
      container_name: backend
      build: ./backend
      restart: always
      volumes:
        - .:/backend
        - static_volume:/backend/static
        - media_volume:/backend/media
      links:
        - db
        - redis
      depends_on:
        - db
        - redis
      networks:
        - nginx_network
        - database_network
        - redis_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  pgdata:
  redisdata:
  static_volume:
  media_volume: