version: '3'
services:

    db:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_PASSWORD: password123
      # ports:
      #   - "5432:5432"
      #   (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: nginx
        build: ./nginx
        restart: always
        ports:
        - "8080:80"
        # - "80:80"
        volumes:
        - api_data:/docker_api
        - ./log:/var/log/nginx
        depends_on:
        - backend

    backend:
        container_name: backend
        build: ./backend
        restart: always
        # command: uwsgi  --emperor uwsgi.ini
        command: uwsgi --ini uwsgi.ini
        # ports:
        # - "8002:8000"
        volumes:
        - api_data:/docker_api
        depends_on:
        - db

volumes:
    api_data:
    pgdata: