# Generated by Django 2.2 on 2019-07-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='flag',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
