# Generated by Django 2.2 on 2019-07-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190703_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryId',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variantId',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
