# Generated by Django 2.2 on 2019-07-25 12:14

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190725_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='adult_price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]), size=6),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='child_price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]), size=6),
        ),
    ]
