# Generated by Django 2.2 on 2019-07-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190710_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='productID',
            new_name='variantID',
        ),
    ]
