# Generated by Django 2.2 on 2019-07-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_ppoi',
        ),
    ]
