# Generated by Django 2.2 on 2019-07-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190705_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variantId',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
