# Generated by Django 2.2 on 2019-07-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190711_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='description',
        ),
    ]
