# Generated by Django 2.2 on 2019-07-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190705_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variantId',
        ),
        migrations.AddField(
            model_name='category',
            name='sortNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sortNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sortNo',
            field=models.IntegerField(default=0),
        ),
    ]
