# Generated by Django 2.2 on 2019-07-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productvariant_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
