# Generated by Django 2.2 on 2019-07-06 12:19

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190706_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
