# Generated by Django 2.2 on 2019-07-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190706_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
