# Generated by Django 2.2 on 2019-07-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190705_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sortNo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sortNo',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='sortNo',
        ),
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='productID',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
