# Generated by Django 2.2 on 2019-07-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190714_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, '美食'), (2, '门票'), (3, '日游'), (4, '用车'), (5, '酒店'), (6, '伴手礼')], default=1),
        ),
    ]
