# Generated by Django 2.2 on 2019-07-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190705_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_ppoi',
            new_name='photo_ppoi',
        ),
    ]
