# Generated by Django 2.2 on 2019-07-06 10:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190706_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
