# Generated by Django 2.2 on 2019-07-21 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190714_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='adultPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='adultQuantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='adult_desc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='childPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='childQuantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='child_desc',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
