# Generated by Django 2.2 on 2019-07-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190721_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='hasChild',
            field=models.BooleanField(default=False),
        ),
    ]
