# Generated by Django 2.2 on 2019-07-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productvariant_haschild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='online',
            new_name='on',
        ),
        migrations.AddField(
            model_name='product',
            name='on',
            field=models.BooleanField(default=True),
        ),
    ]
