# Generated by Django 2.2 on 2019-07-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190721_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='on',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='on',
            new_name='status',
        ),
    ]
