# Generated by Django 2.2 on 2019-07-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190721_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='adultPrice',
            new_name='adult_price',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='adultQuantity',
            new_name='adult_quantity',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='childPrice',
            new_name='child_price',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='childQuantity',
            new_name='child_quantity',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='hasChild',
            new_name='child_status',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='adult_status',
            field=models.BooleanField(default=True),
        ),
    ]
