# Generated by Django 2.2 on 2019-07-25 09:13

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20190722_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='adult_price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]), default=0, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='child_price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]), default=0, size=None),
            preserve_default=False,
        ),
    ]
