# Generated by Django 2.2 on 2019-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionentity',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
