# Generated by Django 2.2 on 2019-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, '公司用户'), (2, '个人用户'), (3, '员工')], default=2),
        ),
    ]
