# Generated by Django 2.2 on 2019-08-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='createTime',
        ),
        migrations.RemoveField(
            model_name='role',
            name='deleted',
        ),
    ]
