# Generated by Django 2.2 on 2019-07-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, '个人用户'), (2, '公司用户'), (3, '员工')], default=1),
        ),
    ]
