# Generated by Django 2.2 on 2019-08-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_actionentity_enable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionentity',
            old_name='describe',
            new_name='label',
        ),
    ]
