# Generated by Django 2.2 on 2019-07-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_customuser_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
