# Generated by Django 2.2 on 2019-07-27 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190725_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='price_level',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
