# Generated by Django 2.2 on 2019-08-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190804_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionentity',
            name='defaultCheck',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='actionEntitySet',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='actionentity',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actionEntitySet', to='authorization.Permission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='authorization.Role'),
            preserve_default=False,
        ),
    ]
