# Generated by Django 2.2 on 2019-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190724_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='price_level',
            field=models.IntegerField(default=0),
        ),
    ]
