# Generated by Django 2.2 on 2019-08-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20190805_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionentity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-id']},
        ),
    ]
