# Generated by Django 2.2 on 2019-07-01 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20190701_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=32, null=True)),
                ('describe', models.CharField(blank=True, max_length=32, null=True)),
                ('defaultCheck', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('describe', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(default=0)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionId', models.CharField(blank=True, max_length=32, null=True)),
                ('permissionName', models.CharField(blank=True, max_length=32, null=True)),
                ('actionEntitySet', models.ManyToManyField(blank=True, null=True, related_name='permission', to='authorization.ActionEntity')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='authorization.Role'),
        ),
    ]
