# Generated by Django 2.2 on 2019-07-02 08:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20190701_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='actionData',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
