# Generated by Django 2.2 on 2019-07-02 08:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_permission_actiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='actionData',
            field=jsonfield.fields.JSONCharField(blank=True, max_length=512, null=True),
        ),
    ]
