# Generated by Django 2.2 on 2019-07-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20190702_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='actionData',
        ),
    ]
