# Generated by Django 2.2 on 2019-07-25 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('confirmId', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('changeAt', models.DateTimeField(auto_now=True)),
                ('adultQuantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('childQuantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
