# Generated by Django 2.2 on 2019-07-29 06:15

import app.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(default=app.order.models.create_uuid, max_length=64),
        ),
    ]
