# Generated by Django 2.2 on 2019-07-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190727_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
