# Generated by Django 2.2 on 2019-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190727_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '新建'), (1, '订单已确认'), (2, '出票成功'), (3, '出票失败'), (4, '订单已取消')], default=0),
        ),
    ]
