# Generated by Django 2.2 on 2019-07-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190728_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '部分支付'), (2, '全部付清'), (3, '部分退款'), (4, '全部退款')], default=0),
        ),
    ]
