# Generated by Django 2.2 on 2019-07-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='source',
        ),
    ]
