# Generated by Django 2.2 on 2019-07-08 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20190706_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
