# Generated by Django 2.2 on 2019-09-23 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(blank=True, max_length=64, null=True)),
                ('order_status', models.IntegerField(choices=[(0, '新建'), (1, '订单已确认'), (2, '出票成功'), (3, '订单已取消'), (4, '退款中'), (5, '已退款')], default=0)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('change_at', models.DateTimeField(auto_now=True)),
                ('guest_info', models.TextField(blank=True, null=True)),
                ('guest_contact', models.TextField(blank=True, null=True)),
                ('guest_remark', models.TextField(blank=True, null=True)),
                ('adult_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('adult_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('adult_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('child_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('child_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('child_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remark', models.TextField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=128, null=True)),
                ('variant', models.CharField(blank=True, max_length=64, null=True)),
                ('productID', models.CharField(blank=True, max_length=16, null=True)),
                ('variantID', models.CharField(blank=True, max_length=16, null=True)),
                ('category', models.IntegerField(choices=[(1, '美食'), (2, '门票'), (3, '日游'), (4, '用车'), (5, '酒店'), (6, '伴手礼')], default=1)),
                ('sku', models.CharField(blank=True, max_length=32, null=True)),
                ('customer', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=150, null=True)),
                ('operator_id', models.IntegerField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('order_from', models.CharField(blank=True, default='ugodubai', max_length=64, null=True)),
                ('relatedID', models.CharField(blank=True, max_length=64, null=True)),
                ('offer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('guest_relatedID', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-id', 'relatedID'],
            },
        ),
    ]
