# Generated by Django 2.2.4 on 2019-09-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmID',
        ),
    ]
