# Generated by Django 2.2.4 on 2019-08-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_contact',
            new_name='guest_contact',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_info',
            new_name='guest_info',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='order',
            name='variant',
        ),
    ]
