# Generated by Django 2.2.4 on 2019-08-26 14:08

import app.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190826_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default=app.order.models.create_uuid, max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='productID',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.CharField(default=app.order.models.create_uuid, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='variantID',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
