# Generated by Django 2.2.4 on 2019-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190910_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
