# Generated by Django 2.2.4 on 2019-08-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190826_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total',
        ),
    ]
