# Generated by Django 2.2.4 on 2019-08-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190826_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.IntegerField(choices=[(1, '美食'), (2, '门票'), (3, '日游'), (4, '用车'), (5, '酒店'), (6, '伴手礼')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='variant',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
