# Generated by Django 2.2.4 on 2019-09-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190917_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_status',
        ),
    ]
