# Generated by Django 2.2.4 on 2019-08-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190826_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sku',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
