# Generated by Django 2.2.4 on 2019-09-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='relatedID',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
