# Generated by Django 2.2.4 on 2019-09-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_relatedid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id', '-relatedID']},
        ),
    ]
