# Generated by Django 2.2.4 on 2019-08-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190826_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='remark',
            new_name='guest_remark',
        ),
    ]
