# Generated by Django 2.2.4 on 2019-08-26 14:38

import app.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(blank=True, default=app.order.models.create_uuid, max_length=64, null=True),
        ),
    ]
