# Generated by Django 2.2.4 on 2019-08-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='productID',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='variant_id',
            new_name='variantID',
        ),
    ]
