# Generated by Django 2.2.4 on 2019-08-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190827_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sku',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
