# Generated by Django 2.2 on 2019-10-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('captured', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.IntegerField(choices=[(0, '未支付'), (1, '部分支付'), (2, '全部付清'), (3, '退款中'), (4, '部分退款'), (5, '全部退款')], default=0)),
                ('action', models.IntegerField(choices=[(0, '扣费'), (1, '退款'), (2, '充值')], default=0)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('change_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('customer_balance', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-id'],
            },
        ),
    ]
