# Generated by Django 2.2.4 on 2019-09-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='captured',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=9),
        ),
    ]
