# Generated by Django 2.2.4 on 2019-09-18 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('70d8c7a1-d01f-439d-be73-6fc9ce37f444'), max_length=36),
        ),
    ]
