# Generated by Django 2.2.4 on 2019-09-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190918_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='token',
        ),
    ]
