# Generated by Django 2.2 on 2019-09-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190922_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='action',
            field=models.CharField(choices=[(0, '捕捉'), (1, '退款'), (2, '充值')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_balance',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[(0, '未支付'), (1, '部分支付'), (2, '全部付清'), (3, '退款中'), (4, '部分退款'), (5, '全部退款')], default=0, max_length=10),
        ),
    ]
