# Generated by Django 2.2 on 2019-09-22 10:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponID', models.CharField(blank=True, max_length=16, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('exp_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.ManyToManyField(related_name='coupon', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='product.ProductVariant')),
            ],
            options={
                'db_table': 'coupon',
                'ordering': ['-id'],
            },
        ),
    ]
